# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f4f3a81545557aa274edf319e0190896cd2063cccb86c28519732a2a8fbe725a763e21390d512e21c36269b74420b0960cff5d4cd4ee64976dc4374066662ff

test:
  secret_key_base: 4632f95896a8b00cac6443195994a1cb43fc593a13fac3aa644ac582bb5cc8d4c3e771454b6f5b795727b790bbe84867d7e7e68eda6d4632e8f6873828b78dd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
